import { SjclCipherEncrypted } from 'sjcl';
import type { StringUInt64 } from '../types/SpecialStrings.d';
interface LocalStoreSchema {
    [key: string]: {
        type: 'string' | 'array' | 'boolean';
    };
}
export declare const schemaKeys: {
    ENCRYPTED_CONTACTS: string;
    ENCRYPTED_PASSPHRASE: string;
    ENCRYPTED_PIN: string;
    FULL_SERVICE_BINARIES_PATH: string;
    FULL_SERVICE_DB_EXISTS: string;
    FULL_SERVICE_DB_PATH: string;
    FULL_SERVICE_LEDGER_DB_PATH: string;
    GIFT_CODES: string;
    LEAVE_FULL_SERVICE_RUNNING: string;
    LEDGER_DB_PATH: string;
    NAME: string;
    OFFLINE_START: string;
    PIN_THRESHOLD_PMOB: string;
    SALT: string;
    THEME: string;
};
export declare const schema: LocalStoreSchema;
export declare const setStore: (newStore: Store) => void;
export declare const setOfflineStart: (startOffline: boolean) => void;
export declare const getOfflineStart: () => boolean;
export declare const getEncryptedContacts: () => SjclCipherEncrypted;
export declare const setEncryptedContacts: (encryptedContacts: SjclCipherEncrypted) => void;
export declare const deleteEncryptedContacts: () => void;
export declare const getGiftCodes: () => Array<string>;
export declare const setGiftCodes: (giftCodes: Array<string>) => void;
export declare const getEncryptedPin: () => SjclCipherEncrypted | undefined;
export declare const setEncryptedPin: (encryptedPin: SjclCipherEncrypted) => void;
export declare const deleteEncryptedPin: () => void;
export declare const getLeaveFullServiceRunning: () => boolean;
export declare const setLeaveFullServiceRunning: (leaveFullServiceRunning: boolean) => void;
export declare const getPinThresholdPmob: () => StringUInt64;
export declare const setPinThresholdPmob: (pinThresholdPmob: StringUInt64) => void;
export declare const deletePinThresholdPmob: () => void;
export declare const getLedgerDbPath: () => string;
export declare const getTheme: () => string;
export declare const getEncryptedPassphrase: () => SjclCipherEncrypted | undefined;
export declare const setEncryptedPassphrase: (encryptedPassphrase: SjclCipherEncrypted) => void;
export declare const deleteEncryptedPassphrase: () => void;
export declare const getFullServiceDbPath: () => string;
export declare const getWalletDbExists: () => boolean;
export declare const getFullServiceLedgerDbPath: () => string;
export declare const getFullServiceBinariesPath: () => string;
export declare const setFullServiceBinariesPath: (name: string) => void;
export declare const setLedgerDbPath: (name: string) => void;
export declare const setFullServiceDbPath: (name: string) => void;
export declare const getName: () => string;
export declare const setName: (name: string | null) => void;
export declare const getSalt: () => string;
export declare const setSalt: (salt: string) => void;
export declare const setTheme: (theme: 'system' | 'light' | 'dark') => void;
export {};
